import React, { Component } from 'react'
import { connect } from "react-redux"
import { compose } from "recompose"

import App from '../form-component/App'
import BlankSpace from '../form-component/BlankSpace'

import evaluator from "../../util/evaluator"
import { fetchAllData } from "../../data-accessor/formDataGet"
import ActionList from "../../reducer/actionList"

import { TabStrip, TabStripTab } from '@progress/kendo-react-layout'

class PageNavigator extends Component {

  getLastAppState() {
    return this.props.appState[this.props.appState.length - 1]
  }

  getCurrentDescription() {
    return this.props.description[this.getLastAppState()]
  }

  getCurrentPageIndex(navBar) {
    var currentPage = this.getLastAppState()
    /**
     * looking for hidden page so we can get the correct page index for the TabStrip
     **/
    var hiddenPageIndexes = []
    for(let index in navBar) {
      if(navBar[index] === 0) {
        hiddenPageIndexes.push(index)
      }
    }
    /**
     * Adjusting currentPage so it gets the correct index.
     **/
    for(let index in hiddenPageIndexes) {
      if(currentPage > hiddenPageIndexes[index]) {
        currentPage--
      }
    }
    return currentPage
  }

  render() {
    var isLastPage = false
    const current = this.getCurrentDescription()
    const content = <div>
      <h2>{current.pagename}</h2>
      <App form={current.form} />
    </div>
    const navBar = this.props.description.map((p, index) => {
      if(index === this.getLastAppState()) {
        isLastPage = true
        return <TabStripTab key={index}  disabled={true} title={p.pagename}>{content}</TabStripTab>
      } else if(index >= this.getLastAppState()) {
        if(p.hasOwnProperty("rendered")) {
          if(!evaluator(p.rendered)) {
            this.props.popData(index)
            /**
             * returns an empty element
             */
            return 0;
          }
        }
        if(isLastPage) {
          isLastPage = false
        }
        return <TabStripTab key={index}  disabled={true} title={p.pagename}>{content}</TabStripTab>
      } else {
        if(p.hasOwnProperty("rendered")) {
          if(!evaluator(p.rendered)) {
            this.props.popData(index)
            /**
             * returns an empty element
             */
            return 0;
          }
        }
        return <TabStripTab key={index} onClick={() => this.jumpButtonListener(index)} title={p.pagename}>{content}</TabStripTab>
      }
    })

    return <div>
      <TabStrip selected={this.getCurrentPageIndex(navBar)} onSelect={(e) => this.jumpButtonListener(e.selected)}>
        {navBar.filter(nav => nav !== 0)}
      </TabStrip>
      <BlankSpace space="75px" />
      <div className="k-form-field navFooter">
        <button className="k-button k-primary" onClick={() => this.nextButtonListener()}>{isLastPage ? "FINISH" : "NEXT"}</button>
        {this.props.appState.length > 1 ? <button className="k-button" onClick={() => this.prevButtonListener()}>PREV</button> : ""}
      </div>
    </div>
  }

  jumpButtonListener(index) {
    var target = this.props.appState.findIndex(element => {
      return element === index
    })
    this.props.popState((this.props.appState.length-1) - target)
  }

  prevButtonListener() {
    this.props.popState(1)
  }

  /**
   * [MOTI]
   * temporary method to show the final output data generated by the app
   * flush all data stored in app state into a pop up dialog
   */
  generateJSON() {
    alert(JSON.stringify(fetchAllData()));
  }

  nextButtonListener() {
    for(var i = this.getLastAppState() + 1; i < this.props.description.length; i++) {
      if(this.props.description[i].hasOwnProperty("rendered")) {
        if(evaluator(this.props.description[i].rendered)) {
          this.props.pushState(i)
          return
        }
      } else {
        this.props.pushState(i)
        return
      }
    }
    this.generateJSON()
  }
}

const mapStateToProps = function(storage) {
  return {
    notifier: storage.form.notifier,
    appState: storage.form.app_state
  }
}

const mapDispatchToProps = (dispatch) => {
  return {
    setDescription: (desc) => dispatch({
      type: ActionList.SET_DESCRIPTION,
      payload: desc
    }),
    pushState: (index) => dispatch({
      type: ActionList.PUSH_APP_STATE,
      payload: {
        "index": index
      }
    }),
    popState: (index) => dispatch({
      type: ActionList.POP_APP_STATE,
      payload: {
        "index": index
      }
    }),
    popData: (index) => dispatch({
      type: ActionList.POP_DATA_BY_INDEX,
      payload: {
        "index": index
      }
    })
  }
}

export default compose(
  connect(
    mapStateToProps,
    mapDispatchToProps,
  )
)(PageNavigator)
