export default({

  GO_TO_DESC_LIST:            "go_to_desc_list",
  GO_TO_CONFIG_LIST:          "go_to_config_list",
  GO_TO_IMPORT_CONFIG:        "go_to_import_config",
  GO_TO_NEW_DESC_CONTENT:     "go_to_new_desc_content",
  GO_TO_NEW_TEMPLATE:         "go_to_new_template",
  GO_TO_HOMEPAGE:             "go_to_homepage",
  ON_FORM_EXIT:               "exiting_form_selector",

  FETCH_CONFIGS:              "fetch_configs",
  ON_CONFIGS_FETCHED:         "configs_fetched",
  ON_CONFIGS_FETCH_FAIL:      "fetch_configs_fail",
  ASSIGN_CONFIG:              "assign_config",
  DELETE_CONFIG:              "delete_config",
  ON_CONFIG_DELETED:          "on_config_deleted",
  ON_CONFIG_DELETE_FAIL:      "on_config_delete_fail",
  CHANGE_CURRENT_CONFIG_NAME: "change_config_name",
  SAVE_CONFIG:                "save_config",
  ON_CONFIG_SAVED:            "config_saved",
  ON_CONFIG_SAVE_FAIL:        "config_save_fail",
  // IMPORT_CONFIG:              "import_config",
  // ON_CONFIG_IMPORTED:         "config_imported",
  // ON_CONFIG_IMPORT_FAIL:      "config_import_fail",
  ADD_NEW_CONFIG:             "new_config",

  SET_DATA:                   "set_data",
  POP_DATA:                   "remove_data",
  ADD_PATH:                   "add_path",
  REMOVE_PATH:                "remove_path",
  CLEAR_DATA:                 "destroy_all_data",
  ADD_EXT_FILE_REF:           "add_external_file_reference",
  REMOVE_EXT_FILE_REF:        "remove_external_file_reference",
  ADD_REMOVED_EXT_FILE_REF:   "add_removed_external_file_reference",

  FETCH_DESCRIPTIONS:         "fetch_descs",
  ON_DESCRIPTIONS_FETCHED:    "descs_fetched",
  ON_DESCRIPTIONS_FETCH_FAIL: "fetch_descs_fail",
  ASSIGN_DESCRIPTION:         "assign_description",
  ASSIGN_DESC_CONTENT:        "assign_desc_content",
  ASSIGN_TEMPLATE:            "assign_template",
  ADD_NEW_DESCRIPTION:        "new_description",
  ADD_NEW_DESC_CONTENT:       "new_description_content",
  ADD_NEW_TEMPLATE:           "new_template",

  SAVE_DESCRIPTION:           "save_description",
  ON_DESCRIPTION_SAVED:       "description_saved",
  ON_DESCRIPTION_SAVE_FAIL:   "description_save_fail",
  DELETE_DESCRIPTION:         "delete_description",
  ON_DESCRIPTION_DELETED:     "description_deleted",
  ON_DESCRIPTION_DELETE_FAIL: "description_delete_fail",

  SAVE_DESCRIPTION_CONTENT:           "save_description_content",
  ON_DESCRIPTION_CONTENT_SAVED:       "description_content_saved",
  ON_DESCRIPTION_CONTENT_SAVE_FAIL:   "description_content_save_fail",
  DELETE_DESCRIPTION_CONTENT:         "delete_description_content",
  ON_DESCRIPTION_CONTENT_DELETED:     "description_content_deleted",
  ON_DESCRIPTION_CONTENT_DELETE_FAIL: "description_content_delete_fail",

  SAVE_TEMPLATE:               "save_template",
  ON_TEMPLATE_SAVED:           "template_saved",
  ON_TEMPLATE_SAVE_FAIL:       "template_save_fail",
  DELETE_TEMPLATE:             "delete_template",
  ON_TEMPLATE_DELETED:         "template_deleted",
  ON_TEMPLATE_DELETE_FAIL:     "template_delete_fail",

  ON_LOGIN:                    "login",
  ON_LOGIN_SUCCESS:            "login_success",
  ON_LOGIN_FAIL:               "login_fail",
  ON_LOGOUT:                   "logout",

  SET_DIALOG_MESSAGE:          "set_dialog_message",
  SET_ADDITIONAL_METHOD:       "set_methods",
  SET_DIALOG_DEFAULT:          "revert_default",

  SET_WINDOW:                  "set_window",
  SET_WINDOW_CONTENT:          "set_window_content",
  SET_WINDOW_SIZE:             "set_window_size",
  SET_WINDOW_DEFAULT:          "set_window_default"
})
